# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 227fa7208e609f8d2a2eac85bb2bca22f1800e38bd072bf8503a6cfbd2026ccac63918cdadca81e7168a04de0ad9348f02c3e4c9f1218b00e9aafe12769e9516

test:
  secret_key_base: 43afb2ca7d6cd41b7a1a78e4a7d7b21a017e70a2139792640e1968663cf77850247502e5ead6868445fc4b9f7a471e51b1fc96ca8798b866a264901769d21c7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
